// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Message struct {
	ID       int64     `json:"id"`
	RoomID   string    `json:"room_id"`
	Author   string    `json:"author"`
	Content  string    `json:"content"`
	SendedAt time.Time `json:"sended_at"`
}

type Room struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	IsDm      bool      `json:"is_dm"`
	CreatedAt time.Time `json:"created_at"`
}

type RoomParticipant struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
