// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddRoomParticipant(ctx context.Context, arg AddRoomParticipantParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetDMParticipants(ctx context.Context, roomID string) ([]string, error)
	GetHistory(ctx context.Context, roomID string) ([]GetHistoryRow, error)
	GetRoomMetadata(ctx context.Context, id string) (GetRoomMetadataRow, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsRoomParticipant(ctx context.Context, arg IsRoomParticipantParams) (bool, error)
	ListRooms(ctx context.Context) ([]ListRoomsRow, error)
	ListUserDMs(ctx context.Context, userID string) ([]ListUserDMsRow, error)
	RoomExistsByName(ctx context.Context, name string) (bool, error)
	SaveMessage(ctx context.Context, arg SaveMessageParams) error
	UserExistsByID(ctx context.Context, id string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
