// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const addRoomParticipant = `-- name: AddRoomParticipant :exec
INSERT INTO room_participants (room_id, user_id)
VALUES ($1, $2)
`

type AddRoomParticipantParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) AddRoomParticipant(ctx context.Context, arg AddRoomParticipantParams) error {
	_, err := q.db.Exec(ctx, addRoomParticipant, arg.RoomID, arg.UserID)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (id, name, is_dm)
VALUES ($1, $2, $3)
`

type CreateRoomParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	IsDm bool   `json:"is_dm"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.Exec(ctx, createRoom, arg.ID, arg.Name, arg.IsDm)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, password, name, role)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Name     string `json:"name"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Name,
		arg.Role,
	)
	return err
}

const getDMParticipants = `-- name: GetDMParticipants :many
SELECT user_id
FROM room_participants
WHERE room_id = $1
ORDER BY user_id
`

func (q *Queries) GetDMParticipants(ctx context.Context, roomID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getDMParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHistory = `-- name: GetHistory :many
SELECT room_id, author, content, sended_at
FROM messages
WHERE room_id = $1
ORDER BY sended_at
`

type GetHistoryRow struct {
	RoomID   string    `json:"room_id"`
	Author   string    `json:"author"`
	Content  string    `json:"content"`
	SendedAt time.Time `json:"sended_at"`
}

func (q *Queries) GetHistory(ctx context.Context, roomID string) ([]GetHistoryRow, error) {
	rows, err := q.db.Query(ctx, getHistory, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHistoryRow{}
	for rows.Next() {
		var i GetHistoryRow
		if err := rows.Scan(
			&i.RoomID,
			&i.Author,
			&i.Content,
			&i.SendedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomMetadata = `-- name: GetRoomMetadata :one
SELECT id, name, is_dm
FROM rooms
WHERE id = $1
`

type GetRoomMetadataRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	IsDm bool   `json:"is_dm"`
}

func (q *Queries) GetRoomMetadata(ctx context.Context, id string) (GetRoomMetadataRow, error) {
	row := q.db.QueryRow(ctx, getRoomMetadata, id)
	var i GetRoomMetadataRow
	err := row.Scan(&i.ID, &i.Name, &i.IsDm)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, name, role, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, name, role, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const isRoomParticipant = `-- name: IsRoomParticipant :one
SELECT EXISTS(
    SELECT 1 FROM room_participants
    WHERE room_id = $1 AND user_id = $2
)
`

type IsRoomParticipantParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) IsRoomParticipant(ctx context.Context, arg IsRoomParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isRoomParticipant, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, is_dm
FROM rooms
WHERE is_dm = false
ORDER BY created_at
`

type ListRoomsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	IsDm bool   `json:"is_dm"`
}

func (q *Queries) ListRooms(ctx context.Context) ([]ListRoomsRow, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsRow{}
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsDm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDMs = `-- name: ListUserDMs :many
SELECT r.id, r.name, r.is_dm
FROM rooms r
JOIN room_participants rp ON rp.room_id = r.id
WHERE r.is_dm = true AND rp.user_id = $1
ORDER BY r.created_at
`

type ListUserDMsRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	IsDm bool   `json:"is_dm"`
}

func (q *Queries) ListUserDMs(ctx context.Context, userID string) ([]ListUserDMsRow, error) {
	rows, err := q.db.Query(ctx, listUserDMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDMsRow{}
	for rows.Next() {
		var i ListUserDMsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsDm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomExistsByName = `-- name: RoomExistsByName :one
SELECT EXISTS(SELECT 1 FROM rooms WHERE name = $1)
`

func (q *Queries) RoomExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, roomExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const saveMessage = `-- name: SaveMessage :exec
INSERT INTO messages (room_id, author, content, sended_at)
VALUES ($1, $2, $3, $4)
`

type SaveMessageParams struct {
	RoomID   string    `json:"room_id"`
	Author   string    `json:"author"`
	Content  string    `json:"content"`
	SendedAt time.Time `json:"sended_at"`
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) error {
	_, err := q.db.Exec(ctx, saveMessage,
		arg.RoomID,
		arg.Author,
		arg.Content,
		arg.SendedAt,
	)
	return err
}

const userExistsByID = `-- name: UserExistsByID :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserExistsByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
